spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

